apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa
  labels:
    app.kubernetes.io/name: orders-sa
    app.kubernetes.io/instance: orders
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com
