apiVersion: v1
kind: Service
metadata:
  name: orders-rabbitmq-svc
  labels:
    app.kubernetes.io/name: orders-postgresql-svc
    app.kubernetes.io/instance: orders-postgresql
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: amqp
      protocol: TCP
      name: tcp-amqp
    - port: 15672
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: orders-rabbitmq
    app.kubernetes.io/instance: orders
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com


