apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-configmap
  labels:
    app.kubernetes.io/name: catalog-app
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: "in-memory"
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: ""
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: "catalogdb"
  RETAIL_CATALOG_PERSISTENCE_USER: "catalog_user"
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: ""
  RETAIL_CATALOG_PERSISTENCE_CONNECT_TIMEOUT: "5"