apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkout-sa
  labels:
    app.kubernetes.io/name: checkout-sa
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com