apiVersion: v1 
kind: Service 
metadata:
  name: checkout-redis-svc 
  labels:
      app.kubernetes.io/name: checkout-redis-svc 
      app.kubernetes.io/instance: redis
      app.kubernetes.io/component: app
      app.kubernetes.io/owner: capclouds.com

spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: redis 
  selector:
    app.kubernetes.io/name: checkout-redis
    app.kubernetes.io/instance: checkout
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com