apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts-sa
  labels:
    app.kubernetes.io/name: cart-app
    app.kubernetes.io/instance: cart
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com
