apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-sa
  labels:
    app.kubernetes.io/name: catalog-app
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: catalog-mysql-sa
    app.kubernetes.io/owner: capclouds.com
