apiVersion: v1
kind: Service 
metadata:
  name: catalog-app-svc
  labels:
    app.kubernetes.io/name: catalog-app
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog-app
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com
  ports:
    - name: http
      targetPort: 8080
      protocol: TCP
      port: 8080
