apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-configmap
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: configmap
    app.kubernetes.io/owner: capclouds.com
data:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: "mysql"
  # RETAIL_CATALOG_PERSISTENCE_ENDPOINT: "catalog-mysql:3306"
  RETAIL_CATALOG_PERSISTENCE_ENDPOINT: "mysql-statefulset-0:3306"
  RETAIL_CATALOG_PERSISTENCE_DB_NAME: "catalogdb"
  #RETAIL_CATALOG_PERSISTENCE_USER: "catalog_user"
  #RETAIL_CATALOG_PERSISTENCE_PASSWORD: "mySecretPasswd"
  RETAIL_CATALOG_PERSISTENCE_CONNECT_TIMEOUT: "5"
