apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
  labels:
    app.kubernetes.io/name: catalog-svc
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: headless-svc
    app.kubernetes.io/owner: capclouds.com
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app.kubernetes.io/name: catalog-mysql
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: statefulset
    app.kubernetes.io/owner: capclouds.com
