apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-configmap
data:
  RETAIL_UI_ENDPOINTS_CATALOG: http://catalog-svc
  RETAIL_UI_ENDPOINTS_CARTS: http://carts-svc
  RETAIL_UI_ENDPOINTS_CHECKOUT: http://checkout-svc
  RETAIL_UI_ENDPOINTS_ORDERS: http://orders-svc
