apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui-sa
  labels:
    app.kubernetes.io/name: ui-sa
    app.kubernetes.io/instance: ui-sa
    app.kubernetes.io/component: app
    app.kubernetes.io/owner: capclouds.com